### ISSUE TITLE
[feature] 로그인/회원가입 UI 제작

### ISSUE THREAD

**Issue by LeeJoEun-01** [ssu-it-project/cl-d-iOS#7]
## 💡 Issue

[Auth] 로그인/회원가입 UI 제작 및 Api 연결

## 📝 Todo

- [x] 로그인/회원가입 UI 제작
- [x] splash 화면 제작

**Comment by kimkyuchul** [comment]
UI랑 API 연결이랑 이슈 나눠서 해도 괜찮을듯 지금 너무 양이 커서!  @LeeJoEun-01

**Comment by LeeJoEun-01** [comment]
오케이욥!
